// modifiers.mjs — the modifier layer, the site's "humanizer".
//
// Vic3 effects live in a flat modifier namespace (goods_input_grain_add,
// country_prestige_mult, …) and the game ships the rendering rules itself:
//   - common/modifier_type_definitions/*.txt   → percent / decimals / boolean /
//     color (good = higher-is-better, bad = higher-is-worse, neutral)
//   - localization .../modifiers_l_english.yml → display name per key
//
// Dynamic per-good/per-building keys (goods_input_<good>_add and friends) are
// generated by the engine, not listed in the definitions — matchDynamic()
// reconstructs them. format() is the single entry point every page uses to
// render "what does it do" lines.

import { join } from 'node:path';
import { dataRoot, parseFolder } from './pdx.mjs';
import { titleCase } from './loc.mjs';

export async function loadModifiers(loc) {
  const { entries } = await parseFolder(
    join(dataRoot(), 'game/common/modifier_type_definitions'),
  );
  return new Modifiers(entries, loc);
}

export class Modifiers {
  constructor(defs, loc) {
    this.defs = defs;
    this.loc = loc;
  }

  /** Definition for a key, reconstructing dynamic goods/building keys. */
  def(key) {
    return this.defs[key] || this.matchDynamic(key) || null;
  }

  matchDynamic(key) {
    // goods_input_<good>_add / goods_output_<good>_add / _mult variants:
    // inputs are costs (more input = worse), outputs are gains.
    let m = /^goods_(input|output)_(\w+?)_(add|mult)$/.exec(key);
    if (m) {
      return {
        percent: m[3] === 'mult',
        color: m[1] === 'input' ? 'bad' : 'good',
        _dynamic: { kind: `goods_${m[1]}`, good: m[2] },
      };
    }
    // building_employment_<poptype>_add — jobs per level, neutral bookkeeping.
    m = /^building_employment_(\w+?)_(add|mult)$/.exec(key);
    if (m) {
      return {
        percent: m[2] === 'mult',
        color: 'neutral',
        _dynamic: { kind: 'employment', popType: m[1] },
      };
    }
    return null;
  }

  /** Display name for a modifier key. */
  name(key) {
    const viaLoc = this.loc?.resolve(key);
    if (viaLoc && viaLoc.text.trim()) return viaLoc.text;
    const dyn = this.matchDynamic(key);
    if (dyn) {
      const d = dyn._dynamic;
      if (d.kind === 'goods_input') return `${this.goodName(d.good)} input`;
      if (d.kind === 'goods_output') return `${this.goodName(d.good)} output`;
      if (d.kind === 'employment') return `${this.popName(d.popType)} jobs`;
    }
    return titleCase(key.replace(/_(add|mult)$/, ''));
  }

  goodName(id) { return this.loc?.name(id) ?? titleCase(id); }
  popName(id) { return this.loc?.name(id) ?? titleCase(id); }

  /**
   * Format one modifier for display.
   * Returns { key, label, value, valueText, tone } — tone is 'good' | 'bad' |
   * 'neutral' for the rendered value (direction already applied).
   */
  format(key, value) {
    const def = this.def(key) || {};
    const percent = def.percent === true || def.percent === 'yes';
    const boolean = def.boolean === true || def.boolean === 'yes';
    const decimals = def.decimals ?? (percent ? 0 : 1);

    let valueText;
    if (boolean) {
      valueText = value ? 'yes' : 'no';
    } else {
      const n = Number(value);
      const shown = percent ? n * 100 : n;
      const rounded = Number(shown.toFixed(decimals));
      valueText = `${rounded > 0 ? '+' : ''}${rounded}${percent ? '%' : ''}`;
    }

    const color = def.color || 'neutral';
    let tone = 'neutral';
    if (!boolean && Number(value) !== 0 && color !== 'neutral') {
      const positive = Number(value) > 0;
      tone = (color === 'good') === positive ? 'good' : 'bad';
    }

    return { key, label: this.name(key), value, valueText, tone };
  }

  /** Format a whole { key: value } bag, dropping unknown-and-zero entries. */
  formatBag(bag) {
    return Object.entries(bag ?? {}).map(([k, v]) => this.format(k, v));
  }
}
